### ISSUE TITLE
Camera placement and controller working

### ISSUE THREAD

**Issue by kaushikbalasundar** [IvLabs/person_following_bot#15]
Great job on the package! With a general overview, I could not find documentation on the implementation of this on a custom robot. Where does it assume the camera needs to be mounted and does it depend on the transform from /odom to camera's frame? In the code, I didn't understand how you're calculating these: 

	p_error_l = z - 1.5
	p_error_a = x - 640

Where are these constants, 1.5 an 640 coming from? Does this encode some previously assumed position of the camera?

Thanks!

**Comment by take2rohit** [comment]
So basically these variables are used to compute PID values. 
- Our code doesn't require any camera parameters (intrinsic or extrinsic). So even an uncalibrated depth camera is sufficient to for the code to work
- Our aim was to keep the person about 1.5 meters away from the person. Hence the value 1.5 in `p_error_l` comes from here. We try to basically have a zero error in depth. ()
- The robot moves in such a way that the person always remains at the center of the frame. In our case, the frame size was (1280 x 720). Hence the center of the frame should be `1280/2 = 640`. Therefore we have error in x-direction as `p_error_a = x - 640`

Thanks for the enhancement/ Hope this solves your problem. You can raise a pull request by making these as variables which will be easier for others to understand and maybe add in [README.md](https://github.com/IvLabs/person_following_bot/blob/master/README.md) as well

**Comment by kaushikbalasundar** [comment]
Makes sense, thanks for your prompt response!
