### ISSUE TITLE
yolov3.weights is not found in this project

### ISSUE THREAD

**Issue by AndrewWilesRG** [IvLabs/person_following_bot#7]
Dear sir:
when I ran the follow.py as the instruction said, the error throws out that "no such file or directory : yolov3.weights"

**Comment by take2rohit** [comment]
Thanks @AndrewWilesRG for raising the issue. The weights file can be downloaded from this link:
https://pjreddie.com/media/files/yolov3.weights

We will add this weight link on README.md as well 😺 

Incase of any other issue do let us know.

**Comment by AndrewWilesRG** [comment]
> Thanks @AndrewWilesRG for raising the issue. The weights file can be downloaded from this link:
> https://pjreddie.com/media/files/yolov3.weights
> 
> We will add this weight link on README.md as well 😺
> 
> Incase of any other issue do let us know and feel free to reopen this issue.

thank you, Sir, it is my careless.
