### ISSUE TITLE
Turtlebot deployment issues

### ISSUE THREAD

**Issue by AndrewWilesRG** [IvLabs/person_following_bot#8]
more detail deploy on a turtlebot robot instruction

**Comment by AndrewWilesRG** [comment]
Dear Sir:
I can run your code follow.py successfully, however, this is no detailed instruction about how to run on a turtlebot to control a robot performing   following task. and I use a wifi to connnet the turtlebot and the service PC. so I want to know if it the realsense sensor can be connected to the turtlebot USB and the follow.py is performed on the remove PC as a server. 
I would be grateful if I could get your reply！

**Comment by khush3** [comment]
Hi AndrewWilesRG, 

You need to connect the TurtleBot to a computer using a USB cable and run the `follow.py` script. Presently, the `follow.py` script should be run locally, we have not tested it on a remote machine.

**Comment by khush3** [comment]
I am closing this issue as of now. If you have any further problems, feel free to re-open it.
